sudo: false
language: node_js
node_js:
  - v9
  - v8
  - v6
  - v4
install:
  - npm config set spin=false
  - npm install
script:
  - npm test
after_script:
  - npm install -g coveralls
  - npm run coverage
  - cat ./coverage/lcov.info | coveralls
